[project]
name = "yfinance-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "yfinance>=0.2.65",
    "mcp[cli]",
    "chromadb",
    "smolagents[litellm,mcp]",
]
